### ISSUE TITLE
error

### ISSUE THREAD

**Issue by beenycool** [binnichtaktiv/iPA-Edit#13]
I run the command:python ipaedit.py -i com.toyopagroup.picaboo-12.92.0.46-Decrypted.ipa -o edit.ipa -n Unveil -p appicon.png

it gives me this output:[*] extracting iPA
[*] extracted iPA
[*] current App-Name: Veil
[*] changed app name to: Unveil
[*] changed app icon
[*] exported .dylib(s) successfully!
[*] generating iPA...
Payload path: Payload
Root directory:
Base name: Payload
Traceback (most recent call last):
  File "C:\Users\*******\Downloads\iPA-Edit-main\ipaedit.py", line 318, in <module>
    zip_ipa(ipa_path, payload_path)
  File "C:\Users\*******\\Downloads\iPA-Edit-main\ipaedit.py", line 99, in zip_ipa
    raise ValueError("Invalid directory or base name")
ValueError: Invalid directory or base name

**Comment by binnichtaktiv** [comment]
thanks ill check it. Can you try to use this version until  i fixed it? https://github.com/binnichtaktiv/iPA-Edit/tree/6a6aaabfc0be5cadacb80362b8ccd09aee1bd8d0

**Comment by binnichtaktiv** [comment]
check the latest update it should be fixed

**Comment by beenycool** [comment]
sorry for the late reply thanks
